"""Прогон игры автопилотом и чтение его артефактов — общая машинерия команд `vn test`.

Почему один модуль. Автопилот — единственный законный способ прогнать игру
автоматически (G23: headless-режима у Ren'Py нет, синтетический ввод на рабочий стол
запрещён), и им пользуются пять команд: `test smoke`, `test screens`, `test paths`,
`test replay` и `save corpus`. Пока протокол жил в `cli.py`, каждая новая команда
копировала бы и запуск, и разбор артефактов — то есть пять мест, где можно забыть
почистить `game/generated/qa/` или не заметить `traceback.txt`.

Контракт прогона (артефакты в каталоге `--dir`, пишет рантайм —
`game/framework/00_core/030_flow.rpy`, блок `vn_qa`):
    RESULT.txt    вердикт: «OK: <причина>» или «FAIL: <причина>»
    shot%03d.png  кадры каждого тика
    startup.txt   cold start, секунды (init -> первая интеракция)
    picks.log     фактически взятые выборы: «menu N -> pick K (<menu_id>)»
    state.json    снапшот всех управляемых stores (включая g.scenes_seen)
    gallery.json  {unlocked, total, ids}
    screens.json  тур по экранам: что показали, что не смогли
    perf.json     пик RSS процесса игры
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

from .repo import load_yaml

# Файл автопилота подкладывается в dev-зону генерата и удаляется после прогона.
QA_DIR_REL = "game/generated/qa"
AUTOPILOT_NAME = "autopilot.gen.rpy"
SCREENS_DECL_REL = "content/ui/screens.yaml"
PICK_RE = re.compile(r"^menu (\d+) -> pick (\d+) \((.+)\)$")
# id меню: <chNN>_<sNNN>_m<NNN> (компилятор, scenes.py) — сцена берётся срезом.
MENU_ID_RE = re.compile(r"^(ch\d{2}_s\d{3})_m\d{3}$")

AUTOPILOT_RPY = (
    "# AUTO-GENERATED by vn (test smoke|screens|paths|replay / save corpus) —\n"
    "# временный файл, удаляется после прогона.\n"
    "# Всё гейтится на VN_AUTOPILOT: даже осиротевший .rpyc без env-переменной мёртв.\n"
    "label main_menu:\n"
    "    if not vn_qa.autopilot_active():\n"
    "        $ renpy.quit(save=False)   # осиротевший прогон-файл вне smoke: не играем сами с собой\n"
    "    # Одно выражение, без runtime-import: rollback-лог записал бы модуль в сейв.\n"
    "    $ vn_qa.autopilot_boot()\n"
    "    return\n\n"
    "init python:\n"
    "    if vn_qa.autopilot_active():\n"
    '        config.overlay_screens.append("vn_autopilot")\n\n'
    "screen vn_autopilot():\n"
    "    timer 0.6 action Function(vn_qa.autopilot_tick) repeat True\n"
)


class QaError(RuntimeError):
    """Прогон невозможен (нет SDK, нет генерата, битая декларация)."""


@dataclass
class Pick:
    """Один фактически взятый выбор."""
    menu_index: int
    idx: int
    menu_id: str

    @property
    def scene_id(self) -> str | None:
        m = MENU_ID_RE.match(self.menu_id)
        return m.group(1) if m else None


@dataclass
class RunArtifacts:
    """Прочитанный прогон. Пустые поля = артефакта нет (это тоже факт)."""
    dir: Path
    result: str = "нет RESULT.txt"
    shots: int = 0
    cold_start_s: float | None = None
    picks: list[Pick] = field(default_factory=list)
    state: dict = field(default_factory=dict)
    gallery: dict = field(default_factory=dict)
    screens: dict = field(default_factory=dict)
    perf: dict = field(default_factory=dict)
    traceback: str | None = None

    @property
    def ok(self) -> bool:
        return self.result.startswith("OK") and self.traceback is None


def parse_picks_log(text: str) -> list[Pick]:
    """Трасса выборов из picks.log. Единственный парсер этого формата в проекте."""
    picks: list[Pick] = []
    for line in text.splitlines():
        m = PICK_RE.match(line.strip())
        if m:
            picks.append(Pick(int(m.group(1)), int(m.group(2)), m.group(3)))
    return picks


def _read_json(path: Path) -> dict:
    try:
        doc = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    return doc if isinstance(doc, dict) else {}


def read_run(root: Path, shots: Path) -> RunArtifacts:
    """Артефакты прогона одним объектом — чтобы каждая команда не искала файлы сама."""
    art = RunArtifacts(dir=shots)
    result = shots / "RESULT.txt"
    if result.is_file():
        art.result = result.read_text(encoding="utf-8").strip()
    art.shots = len(list(shots.glob("shot*.png")))
    startup = shots / "startup.txt"
    if startup.is_file():
        try:
            art.cold_start_s = float(startup.read_text(encoding="utf-8").strip())
        except ValueError:
            pass
    picks_log = shots / "picks.log"
    if picks_log.is_file():
        art.picks = parse_picks_log(picks_log.read_text(encoding="utf-8"))
    art.state = _read_json(shots / "state.json")
    art.gallery = _read_json(shots / "gallery.json")
    art.screens = _read_json(shots / "screens.json")
    art.perf = _read_json(shots / "perf.json")
    tb = root / "traceback.txt"
    if tb.is_file():
        art.traceback = tb.read_text(encoding="utf-8", errors="replace")
    return art


def run_failures(art: RunArtifacts, returncode: int, timed_out: bool,
                 timeout_s: int) -> list[str]:
    """Причины считать прогон провалившимся. Порядок — от самой информативной.

    Один список на все команды: раньше каждая решала сама, и «упал с traceback» в
    одной ветке отличался от «не завершился» в другой."""
    fails: list[str] = []
    if art.traceback:
        fails.append("игра упала с traceback (см. traceback.txt)")
    if timed_out:
        fails.append(f"игра не завершилась за {timeout_s} c — прогон снят "
                     f"(дерево процессов убито)")
    elif returncode != 0:
        fails.append(f"движок вернул {returncode}")
    if not art.result.startswith("OK"):
        fails.append(art.result)
    return fails


def tour_screens(root: Path) -> list[dict]:
    """Экраны для тура автопилота из `content/ui/screens.yaml` (qa_screens@1).

    Декларация, а не список в коде: тур нужен трём потребителям (`vn test screens`,
    ночная джоба controller-first, `vn test deck-kit`), и хардкод в каждом из них
    расходился бы — экран, добавленный в игру, тихо оставался бы непроверенным."""
    doc = load_yaml(root / SCREENS_DECL_REL) if (root / SCREENS_DECL_REL).is_file() else None
    if not doc:
        return []
    return [dict(s) for s in (doc.get("screens") or [])]


def autopilot_run(root: Path, shots: Path, extra_env: dict, timeout_s: int,
                  savedir: Path | None = None) -> tuple[int, bool]:
    """Прогон игры автопилотом ВНУТРИ её процесса. Возвращает (returncode, timed_out).

    Никакого синтетического ввода на рабочий стол — только in-process автоматизация
    (G23). Каталог `shots` пересоздаётся: артефакты прошлого прогона, оставшиеся
    рядом с новыми, — это ложные выводы в отчётах."""
    from .doctor import sdk_path

    sdk = sdk_path()
    if sdk is None:
        raise QaError("Ren'Py SDK не найден (RENPY_SDK) — vn doctor подскажет")
    if not (root / "game" / "generated" / "manifest.json").is_file():
        raise QaError("game/generated/ пуст — сначала vn build")

    if shots.exists():
        shutil.rmtree(shots)
    shots.mkdir(parents=True)

    # Пречистка qa/: осиротевший autopilot.rpyc от жёстко убитого прошлого прогона
    # превратил бы обычный vn play в самопроигрывающуюся игру.
    qa_dir = root / QA_DIR_REL
    if qa_dir.exists():
        shutil.rmtree(qa_dir)
    qa_dir.mkdir(parents=True)
    autopilot = qa_dir / AUTOPILOT_NAME
    autopilot.write_text(AUTOPILOT_RPY, encoding="utf-8")

    exe = sdk / ("renpy.exe" if sys.platform == "win32" else "renpy.sh")
    env = dict(os.environ, VN_AUTOPILOT="1", VN_AUTOPILOT_DIR=str(shots), **extra_env)
    cmd = [str(exe), str(root)]
    if savedir is not None:
        cmd += ["--savedir", str(savedir)]
    tb = root / "traceback.txt"
    if tb.is_file():
        tb.unlink()
    timed_out = False
    popen = subprocess.Popen(cmd, env=env, start_new_session=(sys.platform != "win32"))
    try:
        returncode = popen.wait(timeout=timeout_s)
    except subprocess.TimeoutExpired:
        timed_out = True
        returncode = -1
        # renpy.exe — лаунчер: убивать нужно ВСЁ дерево, иначе игра остаётся жить.
        if sys.platform == "win32":
            subprocess.run(["taskkill", "/T", "/F", "/PID", str(popen.pid)],
                           capture_output=True)
        else:
            import signal
            os.killpg(os.getpgid(popen.pid), signal.SIGKILL)
        popen.wait(timeout=10)
    finally:
        for p in (autopilot, autopilot.with_suffix(".rpyc")):
            if p.is_file():
                p.unlink()
        try:
            qa_dir.rmdir()
        except OSError:
            pass
    return returncode, timed_out


# ── Записи прогонов (replay@1) ───────────────────────────────────────────────

REPLAY_DIR_REL = "ci/fixtures/replays"
REPLAY_SUFFIX = ".vnrec.json"


def replay_records(root: Path, name: str | None = None) -> list[tuple[Path, dict]]:
    """[(файл, запись)] из ci/fixtures/replays/. `name` — одна запись.

    Рядом с фикстурами сейвов, а не в отдельном каталоге: это тот же класс данных —
    вход и ожидаемый результат прогона, который едет в git и гоняется в CI."""
    base = root / REPLAY_DIR_REL
    files = sorted(base.glob(f"*{REPLAY_SUFFIX}")) if base.is_dir() else []
    if name:
        want = name if name.endswith(REPLAY_SUFFIX) else f"{name}{REPLAY_SUFFIX}"
        files = [f for f in files if f.name == want]
        if not files:
            raise QaError(f"записи {name!r} нет в {REPLAY_DIR_REL}/ — создайте её: "
                          f"vn test smoke --record {name}")
    out: list[tuple[Path, dict]] = []
    for f in files:
        try:
            out.append((f, json.loads(f.read_text(encoding="utf-8"))))
        except ValueError as e:
            raise QaError(f"{f.relative_to(root).as_posix()}: не читается как JSON ({e})")
    return out


def write_record(root: Path, name: str, why: str, art: RunArtifacts, *,
                 picks: str, lang: str, variant: str, content_version: str,
                 recorded_at: str) -> Path:
    """Запись прогона из УЖЕ прочитанных артефактов: второй прогон не нужен."""
    if not art.ok:
        raise QaError(f"прогон не зелёный ({art.result}) — записывать нечего: запись "
                      f"фиксирует ожидаемый результат, а не текущую поломку")
    doc = {
        "schema": "replay@1",
        "name": name,
        "why": why,
        "recorded_at": recorded_at,
        "content_version": content_version,
        "input": {"picks": [int(x) for x in picks.split(",") if x.strip()]},
        "expect": {
            "result": art.result,
            "picks": [f"{p.menu_id}#{p.idx}" for p in art.picks],
            "state": art.state,
            "gallery_ids": sorted(art.gallery.get("ids") or []),
        },
    }
    if lang:
        doc["input"]["lang"] = lang
    if variant:
        doc["input"]["variant"] = variant
    base = root / REPLAY_DIR_REL
    base.mkdir(parents=True, exist_ok=True)
    path = base / f"{name}{REPLAY_SUFFIX}"
    path.write_text(json.dumps(doc, ensure_ascii=False, indent=1, sort_keys=True) + "\n",
                    encoding="utf-8")
    return path


def replay_diff(root: Path, rec: dict, art: RunArtifacts) -> list[str]:
    """Расхождения повтора с записью. Пустой список = воспроизвелось.

    Версия контента сверяется первой: на другом контенте расхождение состояния
    ничего не доказывает, и молча сравнивать его — значит выдавать ложную панику."""
    from .content.compile import load_manifest  # noqa: F401  (симметрия импортов)

    diffs: list[str] = []
    version = _current_version(root)
    if version and rec.get("content_version") and version != rec["content_version"]:
        return [f"запись сделана на контенте {rec['content_version']}, сейчас "
                f"{version} — сначала перезапишите её (vn test smoke --record), "
                f"сверять состояние между версиями бессмысленно"]
    expect = rec.get("expect") or {}
    if art.result != expect.get("result"):
        diffs.append(f"вердикт: {art.result!r} != {expect.get('result')!r}")
    got_picks = [f"{p.menu_id}#{p.idx}" for p in art.picks]
    if got_picks != list(expect.get("picks") or []):
        diffs.append(f"трасса выборов: {got_picks} != {expect.get('picks')}")
    if art.state != (expect.get("state") or {}):
        for key in sorted(set(art.state) | set(expect.get("state") or {})):
            got, want = art.state.get(key), (expect.get("state") or {}).get(key)
            if got != want:
                diffs.append(f"состояние {key}: {got!r} != {want!r}")
    got_ids = sorted(art.gallery.get("ids") or [])
    if got_ids != list(expect.get("gallery_ids") or []):
        diffs.append(f"галерея: {got_ids} != {expect.get('gallery_ids')}")
    return diffs


def _current_version(root: Path) -> str | None:
    """config.version из генерата (version.gen.rpy) — версия контента прогона."""
    path = root / "game" / "generated" / "version.gen.rpy"
    if not path.is_file():
        return None
    m = re.search(r'define config\.version = "([^"]+)"',
                  path.read_text(encoding="utf-8"))
    return m.group(1) if m else None
