"""PO round-trip (раздел 5, G8): экстракция строк в gettext PO с msgctxt,
импорт переводов в генерируемый game/tl/, псевдолокализация, отчёт покрытия.

Источник истины переводов — loc/po/<lang>/*.po; game/tl/ целиком генерируется
(ручные правки запрещены). msgctxt — стабильный id:
  chNN_sNNN_NNNN        реплика (say-id из исходника)
  chNN_sNNN_mNNN[i]     пункт меню i
  string:<key>          UI/мета-строка из content/ui/strings.yaml
  char:<id>             имя персонажа
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

import polib

from ..repo import load_yaml

GEN_HEADER = "# AUTO-GENERATED by vn loc import. НЕ РЕДАКТИРОВАТЬ: источник — loc/po/.\n"

PSEUDO_MAP = str.maketrans({
    "a": "å", "e": "ê", "i": "ï", "o": "ø", "u": "û", "y": "ý",
    "A": "Å", "E": "Ê", "I": "Ï", "O": "Ø", "U": "Û",
    "а": "ą", "е": "ę", "о": "ǫ", "у": "ų", "и": "į",
    "А": "Ą", "Е": "Ę", "О": "Ǫ", "У": "Ų", "И": "Į",
})


@dataclass
class LocReport:
    changed: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    coverage: dict = field(default_factory=dict)   # lang -> {total, translated, fuzzy}


def _languages(root: Path) -> list[str]:
    cfg = load_yaml(root / "loc" / "loc.yaml")
    return list(cfg.get("languages") or [])


def _ledgers(root: Path) -> dict[str, dict]:
    out = {}
    ledger_dir = root / "loc" / "ledger"
    if ledger_dir.is_dir():
        for f in sorted(ledger_dir.glob("ch*.json")):
            out[f.stem] = json.loads(f.read_text(encoding="utf-8"))
    return out


def _strings(root: Path) -> dict[str, str]:
    f = root / "content" / "ui" / "strings.yaml"
    if not f.is_file():
        return {}
    return dict(load_yaml(f).get("strings") or {})


def _characters(root: Path) -> dict[str, str]:
    out = {}
    for f in sorted((root / "content" / "characters").glob("*/character.yaml")):
        doc = load_yaml(f)
        out[doc["id"]] = doc["name"]
    return out


def _units(root: Path) -> dict[str, list[tuple[str, str, str]]]:
    """domain -> [(msgctxt, msgid, комментарий)]. Домены = имена PO-файлов."""
    domains: dict[str, list[tuple[str, str, str]]] = {}
    for ch_id, ledger in _ledgers(root).items():
        rows = []
        for sid, say in sorted(ledger.get("says", {}).items()):
            who = say.get("who") or "рассказчик"
            rows.append((sid, say["text"], f"говорит: {who}; сцена {sid[:9]}"))
        for mid, menu in sorted(ledger.get("menus", {}).items()):
            for i, caption in enumerate(menu["items"]):
                rows.append((f"{mid}[{i}]", caption, f"пункт меню {i}; сцена {mid[:9]}"))
        domains[ch_id] = rows
    common = []
    for key, text in sorted(_strings(root).items()):
        common.append((f"string:{key}", text, "UI/мета-строка"))
    for char_id, name in sorted(_characters(root).items()):
        common.append((f"char:{char_id}", name, "имя персонажа"))
    if common:
        domains["common"] = common
    return domains


def extract(root: Path) -> LocReport:
    """Обновить PO всех языков из текущих источников: новые строки добавляются,
    изменённые исходники помечаются fuzzy, переводы сохраняются."""
    rep = LocReport()
    langs = _languages(root)
    if not langs:
        rep.warnings.append("loc/loc.yaml: languages пуст — экстрактировать некуда")
        return rep
    domains = _units(root)
    for lang in langs:
        lang_dir = root / "loc" / "po" / lang
        lang_dir.mkdir(parents=True, exist_ok=True)
        for domain, rows in sorted(domains.items()):
            po_path = lang_dir / f"{domain}.po"
            po = polib.pofile(str(po_path)) if po_path.is_file() else polib.POFile()
            po.metadata.setdefault("Content-Type", "text/plain; charset=utf-8")
            po.metadata["Language"] = lang
            existing = {e.msgctxt: e for e in po}
            seen = set()
            dirty = False
            for ctx, msgid, comment in rows:
                seen.add(ctx)
                e = existing.get(ctx)
                if e is None:
                    po.append(polib.POEntry(msgctxt=ctx, msgid=msgid, msgstr="",
                                            comment=comment))
                    dirty = True
                    continue
                if e.obsolete:
                    # Строка вернулась (восстановили сцену/пункт) — переоткрываем.
                    e.obsolete = False
                    dirty = True
                if e.msgid != msgid:
                    # Исходник изменился: перевод остаётся, но помечается fuzzy.
                    e.msgid = msgid
                    if e.msgstr and "fuzzy" not in e.flags:
                        e.flags.append("fuzzy")
                    dirty = True
            for ctx, e in existing.items():
                if ctx not in seen and not e.obsolete:
                    # polib: obsolete — атрибут записи, не флаг
                    e.obsolete = True
                    dirty = True
            if dirty or not po_path.is_file():
                po.save(str(po_path))
                rep.changed.append(po_path.relative_to(root).as_posix())
    return rep


def _load_translations(root: Path, lang: str) -> dict[str, tuple[str, bool]]:
    """msgctxt -> (msgstr, fuzzy) по всем доменам языка (только переведённые)."""
    out: dict[str, tuple[str, bool]] = {}
    lang_dir = root / "loc" / "po" / lang
    if not lang_dir.is_dir():
        return out
    for po_path in sorted(lang_dir.glob("*.po")):
        for e in polib.pofile(str(po_path)):
            if e.obsolete or not e.msgstr:
                continue
            out[e.msgctxt] = (e.msgstr, "fuzzy" in e.flags)
    return out


def _rpy_str(s: str) -> str:
    return ('"' + s.replace("\\", "\\\\").replace('"', '\\"')
            .replace("\n", "\\n").replace("\t", "\\t") + '"')


_INTERP_RE = __import__("re").compile(r"\[([a-zA-Z_][a-zA-Z0-9_.]*)[^\]]*\]")
_TAG_RE = __import__("re").compile(r"\{(/?)([a-zA-Z_#][a-zA-Z0-9_]*)[^{}]*\}")

# Самозакрывающиеся текстовые теги Ren'Py — парного {/x} не требуют
_SELF_CLOSING = {"w", "p", "nw", "fast", "done", "clear", "space", "vspace",
                 "image", "#", "_"}


def _validate_markup(msgid: str, msgstr: str) -> str | None:
    """Битая Ren'Py-разметка в переводе всплывает у ИГРОКА при показе реплики —
    ловим на импорте: парность {тегов} и совпадение набора [подстановок] с исходником."""
    if msgstr.count("{") != msgstr.count("}") or msgstr.count("[") != msgstr.count("]"):
        return "непарные скобки {}/[]"
    stack: list[str] = []
    for m in _TAG_RE.finditer(msgstr):
        closing, name = m.group(1), m.group(2)
        if name in _SELF_CLOSING:
            continue
        if closing:
            if not stack or stack[-1] != name:
                return f"незакрытый/лишний тег {{{closing}{name}}}"
            stack.pop()
        else:
            stack.append(name)
    if stack:
        return f"незакрытые теги: {', '.join('{%s}' % t for t in stack)}"
    src_vars = sorted(_INTERP_RE.findall(msgid))
    dst_vars = sorted(_INTERP_RE.findall(msgstr))
    if src_vars != dst_vars:
        return f"набор [подстановок] расходится с исходником: {src_vars} != {dst_vars}"
    return None


def import_translations(root: Path) -> LocReport:
    """PO -> game/tl/<lang>/: translate-блоки диалогов (по say-id), translate strings
    (имена персонажей), данные меню/строк для рантайм-lookup (vn_loc)."""
    rep = LocReport()
    langs = _languages(root)
    # pseudo доставляется наравне с языками (зеркально compile.py: VN_LANGUAGES)
    if (root / "loc" / "po" / "pseudo").is_dir():
        langs = langs + ["pseudo"]

    # Валидация разметки переводов ДО генерации: битый тег не должен доехать до игрока
    units_by_ctx = {ctx: msgid for rows in _units(root).values() for ctx, msgid, _c in rows}
    for lang in langs:
        if lang == "pseudo":
            continue    # обрамляющие [·] псевдолокализации — намеренные
        for ctx, (msgstr, fuzzy) in _load_translations(root, lang).items():
            if fuzzy or ctx not in units_by_ctx:
                continue
            problem = _validate_markup(units_by_ctx[ctx], msgstr)
            if problem:
                rep.errors.append(f"po/{lang}: {ctx}: {problem}")
    if rep.errors:
        return rep
    tl_root = root / "game" / "tl"
    ledgers = _ledgers(root)
    strings = _strings(root)
    chars = _characters(root)

    expected_files: set[Path] = set()
    for lang in langs:
        tr = _load_translations(root, lang)
        lang_dir = tl_root / lang
        lang_dir.mkdir(parents=True, exist_ok=True)

        # Диалоги: translate <lang> <say_id>
        for ch_id, ledger in sorted(ledgers.items()):
            out = [GEN_HEADER]
            n = 0
            for sid, say in sorted(ledger.get("says", {}).items()):
                if sid not in tr:
                    continue
                text, fuzzy = tr[sid]
                if fuzzy:
                    continue    # fuzzy не поставляется — исходник изменился
                out.append(f"translate {lang} {sid}:")
                who = say.get("who")
                out.append(f"    {who + ' ' if who else ''}{_rpy_str(text)}")
                out.append("")
                n += 1
            path = lang_dir / f"dialogue_{ch_id}.rpy"
            if n:
                expected_files.add(path)
                data = "\n".join(out) + "\n"
                if not path.is_file() or path.read_text(encoding="utf-8") != data:
                    path.write_text(data, encoding="utf-8")
                    rep.changed.append(path.relative_to(root).as_posix())

        # Имена персонажей: translate strings (проходят через _() в Character)
        pairs = [(chars[cid], tr[f"char:{cid}"][0]) for cid in sorted(chars)
                 if f"char:{cid}" in tr and not tr[f"char:{cid}"][1]]
        # Меню и UI-строки: данные для рантайм-lookup vn_loc (НЕ translate strings —
        # коллизии одинаковых текстов между сценами, G8)
        menus_tl = {}
        for ch_id, ledger in sorted(ledgers.items()):
            for mid, menu in sorted(ledger.get("menus", {}).items()):
                items = []
                complete = True
                for i, caption in enumerate(menu["items"]):
                    t = tr.get(f"{mid}[{i}]")
                    if t is None or t[1]:
                        complete = False
                        break
                    items.append(t[0])
                if complete and items:
                    menus_tl[mid] = items
        strings_tl = {key: tr[f"string:{key}"][0] for key in sorted(strings)
                      if f"string:{key}" in tr and not tr[f"string:{key}"][1]}

        out = [GEN_HEADER]
        if pairs:
            out.append(f"translate {lang} strings:")
            for old, new in pairs:
                out.append(f"    old {_rpy_str(old)}")
                out.append(f"    new {_rpy_str(new)}")
            out.append("")
        out.append("init 600 python:")
        out.append(f"    VN_MENUS_TL[{lang!r}] = {menus_tl!r}")
        out.append(f"    VN_STRINGS_TL[{lang!r}] = {strings_tl!r}")
        path = lang_dir / "common.rpy"
        expected_files.add(path)
        data = "\n".join(out) + "\n"
        if not path.is_file() or path.read_text(encoding="utf-8") != data:
            path.write_text(data, encoding="utf-8")
            rep.changed.append(path.relative_to(root).as_posix())

    # Очистка: tl-файлы, которых больше не должно быть (язык убран и т.п.)
    if tl_root.is_dir():
        for f in tl_root.rglob("*.rpy"):
            if f not in expected_files:
                f.unlink()
                for c in (f.with_suffix(".rpyc"),):
                    if c.is_file():
                        c.unlink()
                rep.changed.append(f"удалён: {f.relative_to(root).as_posix()}")
    return rep


_KEEP_RE = __import__("re").compile(r"(\{[^{}]*\}|\[[^\[\]]*\])")


def _pseudoize(s: str) -> str:
    """Акцентирование текста, НЕ трогая {теги} и [подстановки] — иначе pseudo
    ломал бы интерполяции и тестировал бы не UI, а краши."""
    return "".join(
        p if _KEEP_RE.fullmatch(p) else p.translate(PSEUDO_MAP)
        for p in _KEEP_RE.split(s)
    )


def pseudo(root: Path) -> LocReport:
    """Псевдолокализация (QA переполнений UI): язык 'pseudo' с удлинением x1.4."""
    rep = LocReport()
    lang_dir = root / "loc" / "po" / "pseudo"
    lang_dir.mkdir(parents=True, exist_ok=True)
    for domain, rows in sorted(_units(root).items()):
        po = polib.POFile()
        po.metadata["Content-Type"] = "text/plain; charset=utf-8"
        po.metadata["Language"] = "pseudo"
        for ctx, msgid, comment in rows:
            pad = "~" * max(2, int(len(msgid) * 0.4))
            # "[[" — эскейп Ren'Py: голый "[" начал бы интерполяцию и уронил бы текст
            po.append(polib.POEntry(
                msgctxt=ctx, msgid=msgid,
                msgstr=f"[[{_pseudoize(msgid)}{pad}]",
                comment=comment,
            ))
        path = lang_dir / f"{domain}.po"
        po.save(str(path))
        rep.changed.append(path.relative_to(root).as_posix())
    return rep


def report(root: Path) -> LocReport:
    rep = LocReport()
    domains = _units(root)
    total = sum(len(rows) for rows in domains.values())
    langs = _languages(root)
    pseudo_dir = root / "loc" / "po" / "pseudo"
    if pseudo_dir.is_dir():
        langs = langs + ["pseudo"]
    for lang in langs:
        tr = _load_translations(root, lang)
        translated = sum(1 for rows in domains.values() for ctx, _m, _c in rows
                        if ctx in tr and not tr[ctx][1])
        fuzzy = sum(1 for rows in domains.values() for ctx, _m, _c in rows
                    if ctx in tr and tr[ctx][1])
        rep.coverage[lang] = {"total": total, "translated": translated, "fuzzy": fuzzy}
    return rep
