"""vn content compile — Content Compiler.

Фаза 0: version, defaults (named stores), audio, overrides, менюшный реестр, манифест,
инкрементальность и точечная очистка (G6).
Фаза 1: главы и сцены — авторские scene.rpy разбираются парсером Ren'Py через build-bridge
(G24, analyze.py), валидируется контракт C2, эмитится label-обвязка, Chapter/Scene Registry,
персонажи, экран выбора глав.

Контракты генерата:
- каждый файл несёт заголовок AUTO-GENERATED + blake3 источников;
- неизменённые файлы не перезаписываются байтово (иначе Ren'Py перекомпилирует все .rpyc);
- очистка — только по диффу манифестов: удаляются осиротевшие пары .rpy+.rpyc.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path

import blake3

from .. import __version__
from ..repo import git_sha, load_project, load_yaml
from . import scenes as sc
from .analyze import AnalyzeError, analyze_scene_files
from .images import ImagesReport, emit_images, load_locations

MANIFEST_NAME = "manifest.json"
CHAPTER_DIR_RE = re.compile(r"^ch(\d{2})_([a-z][a-z0-9_]{2,30})$")
SCENE_YAML_RE = re.compile(r"^s(\d{3})_([a-z][a-z0-9_]{2,40})\.scene\.yaml$")


class CompileError(RuntimeError):
    pass


@dataclass
class CompileResult:
    written: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)
    deleted: list[str] = field(default_factory=list)
    stale: list[str] = field(default_factory=list)      # только в режиме check
    warnings: list[str] = field(default_factory=list)


def _b3(data: bytes) -> str:
    return blake3.blake3(data).hexdigest()


def _b3_file(path: Path) -> str:
    return _b3(path.read_bytes())


def _header(sources: list[tuple[str, str]]) -> str:
    lines = [
        "# " + "═" * 62,
        f"# AUTO-GENERATED by vn content compile (vn {__version__})",
    ]
    for rel, digest in sources:
        lines.append(f"# source: {rel}  blake3:{digest[:16]}")
    lines += [
        "# НЕ РЕДАКТИРОВАТЬ. Правки перезапишутся. Меняйте источник.",
        "# " + "═" * 62,
        "",
    ]
    return "\n".join(lines)


def _py_literal(value) -> str:
    """YAML-значение -> литерал Python/Ren'Py (в сейве только простые типы, G5)."""
    if isinstance(value, (str, int, float, bool)) or value is None:
        return repr(value)
    if isinstance(value, (list, dict)):
        return repr(value)
    raise CompileError(f"недопустимый тип default-значения: {type(value).__name__}")


# ── Эмиттеры фазы 0 ───────────────────────────────────────────────────────────

def _emit_version(project: dict, sha: str, sources) -> str:
    version = f"{project['version']}+{sha}"
    return _header(sources) + (
        "init offset = -900\n\n"
        f'define config.version = "{version}"\n'
    )


def _emit_defaults(project: dict, var_docs: list[tuple[str, dict]], sources) -> str:
    stores = sorted({doc["store"] for _, doc in var_docs if doc["store"] != "persistent"})
    out = [_header(sources)]
    if stores:
        out.append("# Создание named stores (шкала init-приоритетов — C8/ADR-0003)")
        for store in stores:
            out.append(f"init -980 python in {store}:\n    pass\n")
    for rel, doc in sorted(var_docs):
        store = doc["store"]
        for name, spec in sorted((doc.get("vars") or {}).items()):
            if store == "persistent" and not name.startswith("vn_"):
                # C9: плоская модель persistent.vn_* — без префикса имя запрещено.
                raise CompileError(
                    f"{rel}: persistent-переменная {name!r} обязана начинаться с vn_ (C9)"
                )
            out.append(f"default {store}.{name} = {_py_literal(spec['default'])}")
    out.append("")
    out.append("# Версия схемы сейва (G5): vn_save_schema едет в сейв,")
    out.append("# vn_build_save_schema — константа текущей сборки (сравнение в label after_load).")
    out.append(f"default vn_save_schema = {project['save_schema']}")
    out.append(f"define vn_build_save_schema = {project['save_schema']}")
    return "\n".join(out) + "\n"


def _emit_audio(audio_docs: list[tuple[str, dict]], sources) -> str:
    out = [_header(sources), "init offset = 500\n"]
    n = 0
    for rel, doc in sorted(audio_docs):
        for track_id, spec in sorted((doc.get("tracks") or {}).items()):
            out.append(f'define audio.{track_id} = "{spec["file"]}"')
            n += 1
    if not n:
        out.append("# Треки не объявлены (content/audio/*.yaml пусты).")
    return "\n".join(out) + "\n"


def _emit_menus(menus: dict, strings: dict, languages: list, sources) -> str:
    return _header(sources) + (
        "init offset = -100\n\n"
        "# Реестр choice-id (G8/C1): источник — loc/ledger/ (vn loc keys);\n"
        "# vn_loc.choice_text() делает по нему lookup переводов пунктов меню.\n"
        f"define VN_MENUS = {menus!r}\n\n"
        "# Переводы наполняют tl/<lang>/common.rpy на init 600 (vn loc import).\n"
        "define VN_MENUS_TL = {}\n"
        "define VN_STRINGS_TL = {}\n\n"
        "# UI/мета-строки (content/ui/strings.yaml): vn_loc.t(key) -> текст/перевод.\n"
        f"define VN_STRINGS = {strings!r}\n\n"
        "# Языки для экрана настроек (loc/loc.yaml + pseudo при наличии).\n"
        f"define VN_LANGUAGES = {languages!r}\n"
    )


def _emit_overrides(renames: dict, sources) -> str:
    out = [_header(sources)]
    scene_renames: dict = renames.get("scenes") or {}
    deleted: dict = renames.get("deleted_scenes") or {}
    labels: dict = renames.get("labels") or {}
    overrides = dict(scene_renames)
    overrides.update({old: spec["fallback"] for old, spec in deleted.items()})
    overrides.update(labels)
    out.append("init -100 python:")
    out.append("    # update, а не define: DLC-паки могут дополнять карту (C12).")
    out.append(f"    config.label_overrides.update({overrides!r})")
    out.append("")
    if overrides:
        out.append("# Shim-метки (G7): дают rollback-логу и call-стеку точку опоры,")
        out.append("# которой label_overrides не даёт. Перед jump — размотка стека:")
        out.append("# сейв со старым id и грязным call-стеком не должен тащить лишние кадры.")
        for old, new in sorted(overrides.items()):
            out.append(f"label {old}:\n    $ vn.unwind_call_stack()\n    jump {new}\n")
    else:
        out.append("# Переименований нет — shim-метки не требуются.")
    return "\n".join(out) + "\n"


# ── Сбор контента фазы 1 ─────────────────────────────────────────────────────

def _collect_chapters(root: Path, src, registry, errors: list[str]):
    """Читает content/chapters/: метаданные глав и SceneUnit'ы (без анализа rpy)."""
    chapters: list[dict] = []
    units: list[sc.SceneUnit] = []
    chapters_dir = root / "content" / "chapters"
    if not chapters_dir.is_dir():
        return chapters, units
    for d in sorted(p for p in chapters_dir.iterdir() if p.is_dir()):
        m = CHAPTER_DIR_RE.match(d.name)
        if not m:
            errors.append(f"content/chapters/{d.name}: имя папки вне конвенции (naming.md)")
            continue
        ch_id = f"ch{m.group(1)}"
        ch_yaml = d / "chapter.yaml"
        if not ch_yaml.is_file():
            errors.append(f"content/chapters/{d.name}: нет chapter.yaml")
            continue
        rel, _digest = src(ch_yaml)
        meta = load_yaml(ch_yaml)
        errs = registry.validate(meta, rel)
        if errs:
            errors.extend(errs)
            continue
        chapters.append(meta)

        scenes_dir = d / "scenes"
        seen_short: dict[str, str] = {}
        if scenes_dir.is_dir():
            for f in sorted(scenes_dir.glob("*.scene.yaml")):
                sm = SCENE_YAML_RE.match(f.name)
                if not sm:
                    errors.append(f"{rel}: файл сцены вне конвенции: {f.name}")
                    continue
                if f"s{sm.group(1)}" in seen_short:
                    errors.append(
                        f"content/chapters/{d.name}/scenes: дубликат id s{sm.group(1)}: "
                        f"{seen_short[f's{sm.group(1)}']} и {f.name} — одна из сцен молча "
                        f"выпала бы из генерата"
                    )
                    continue
                seen_short[f"s{sm.group(1)}"] = f.name
                yaml_rel, _d1 = src(f)
                smeta = load_yaml(f)
                s_errs = registry.validate(smeta, yaml_rel)
                if s_errs:
                    errors.extend(s_errs)
                    continue
                rpy = f.parent / (f.name[: -len(".yaml")] + ".rpy")
                if not rpy.is_file():
                    errors.append(f"{yaml_rel}: нет парного .scene.rpy (G3)")
                    continue
                rpy_rel, _d2 = src(rpy)
                short_id = f"s{sm.group(1)}"
                units.append(sc.SceneUnit(
                    full_id=f"{ch_id}_{short_id}",
                    chapter_id=ch_id,
                    short_id=short_id,
                    yaml_rel=yaml_rel,
                    rpy_rel=rpy_rel,
                    meta=smeta,
                    rpy_text=rpy.read_text(encoding="utf-8"),
                    analysis={},
                ))
    return chapters, units


# ── Оркестрация ───────────────────────────────────────────────────────────────

def compile_content(root: Path, out_dir: Path | None = None, check: bool = False) -> CompileResult:
    gen = out_dir if out_dir is not None else root / "game" / "generated"

    from ..schemas import SchemaRegistry
    registry = SchemaRegistry(root / "tools" / "schemas")
    project = load_project(root)
    proj_errors = registry.validate(project, "project.yaml")
    if proj_errors:
        raise CompileError("невалидный project.yaml: " + "; ".join(proj_errors))

    inputs: dict[str, str] = {}

    def src(path: Path) -> tuple[str, str]:
        if not path.is_file():
            raise CompileError(
                f"обязательный вход компилятора отсутствует: {path.relative_to(root).as_posix()} "
                f"(vn content lint обязан это ловить — если нет, это баг линтера)"
            )
        rel = path.relative_to(root).as_posix()
        digest = _b3_file(path)
        inputs[rel] = digest
        return rel, digest

    proj_src = src(root / "project.yaml")
    result = CompileResult()
    errors: list[str] = []

    # Переменные: глобальные + главные (chNN)
    var_docs, var_sources = [], []
    variables_dir = root / "content" / "variables"
    if variables_dir.is_dir():
        for f in sorted(variables_dir.glob("*.vars.yaml")):
            var_sources.append(src(f))
            var_docs.append((f.name, load_yaml(f)))
    for f in sorted((root / "content" / "chapters").glob("*/vars.yaml")):
        rel, _d = src(f)
        var_docs.append((rel, load_yaml(f)))
        var_sources.append((rel, inputs[rel]))

    # Аудио
    audio_docs, audio_sources = [], []
    audio_dir = root / "content" / "audio"
    if audio_dir.is_dir():
        for f in sorted(audio_dir.glob("*.yaml")):
            audio_sources.append(src(f))
            audio_docs.append((f.name, load_yaml(f)))
    audio_ids = {tid for _, doc in audio_docs for tid in (doc.get("tracks") or {})}

    # Персонажи
    char_docs, char_sources = [], []
    for f in sorted((root / "content" / "characters").glob("*/character.yaml")):
        rel, _d = src(f)
        doc = load_yaml(f)
        c_errs = registry.validate(doc, rel)
        if c_errs:
            errors.extend(c_errs)
            continue
        char_docs.append((rel, doc))
        char_sources.append((rel, inputs[rel]))

    renames_path = root / "content" / "renames.yaml"
    renames_src = src(renames_path)
    renames = load_yaml(renames_path)

    # Локализация: ledger'ы (реестр меню), UI-строки, языки
    menus: dict[str, list] = {}
    ledger_dir = root / "loc" / "ledger"
    if ledger_dir.is_dir():
        for f in sorted(ledger_dir.glob("ch*.json")):
            rel, _d = src(f)
            ledger = json.loads(f.read_text(encoding="utf-8"))
            l_errs = registry.validate(ledger, rel)
            if l_errs:
                errors.extend(l_errs)
                continue
            for mid, menu in (ledger.get("menus") or {}).items():
                menus[mid] = list(menu["items"])
    ui_strings: dict[str, str] = {}
    strings_path = root / "content" / "ui" / "strings.yaml"
    if strings_path.is_file():
        rel, _d = src(strings_path)
        ui_strings = dict(load_yaml(strings_path).get("strings") or {})
    languages: list[str] = []
    loc_cfg_path = root / "loc" / "loc.yaml"
    if loc_cfg_path.is_file():
        rel, _d = src(loc_cfg_path)
        languages = list(load_yaml(loc_cfg_path).get("languages") or [])
    if (root / "loc" / "po" / "pseudo").is_dir():
        languages = languages + ["pseudo"]

    # Локации
    locations = load_locations(root, src, registry, errors)

    # Главы и сцены (фаза 1)
    chapters, units = _collect_chapters(root, src, registry, errors)
    if errors:
        raise CompileError(f"{len(errors)} ошибок:\n" + "\n".join(errors))

    char_ids = {doc["id"] for _, doc in char_docs}

    scene_rep = sc.SceneCompileReport()
    scene_outputs: dict[str, str] = {}
    if units:
        try:
            analysis = analyze_scene_files(root, [root / u.rpy_rel for u in units])
        except AnalyzeError as e:
            raise CompileError(str(e))
        known_scenes = {u.full_id for u in units}
        status_by_ch = {c["id"]: c["status"] for c in chapters}
        for u in units:
            u.analysis = analysis.get(str(root / u.rpy_rel).replace("\\", "/"), None) or \
                         analysis.get(str(root / u.rpy_rel), None) or {}
            if not u.analysis:
                scene_rep.errors.append(f"{u.rpy_rel}: build-bridge не вернул анализ")
                continue
            for p in u.meta.get("participants") or []:
                if p not in char_ids:
                    scene_rep.errors.append(
                        f"{u.yaml_rel}: участник {p!r} не объявлен в content/characters/ "
                        f"(say упадёт NameError в рантайме)"
                    )
            dispatch = sc.validate_scene(
                u, known_scenes, status_by_ch.get(u.chapter_id, "draft"), scene_rep
            )
            header = _header([(u.yaml_rel, inputs[u.yaml_rel]), (u.rpy_rel, inputs[u.rpy_rel])])
            scene_outputs[f"scenes/{u.chapter_id}/{u.full_id}.gen.rpy"] = sc.emit_scene(
                u, dispatch, audio_ids, locations, scene_rep, header
            )
        # title_key глав обязан существовать в strings.yaml (иначе в меню — сырой ключ)
        for c in chapters:
            if c["title_key"] not in ui_strings:
                result.warnings.append(
                    f"{c['id']}: title_key {c['title_key']!r} нет в content/ui/strings.yaml — "
                    f"в меню глав отобразится сырой ключ"
                )
        # Валидация глав: entry_scene и scene_order существуют
        for c in chapters:
            ch_scenes = {u.short_id for u in units if u.chapter_id == c["id"]}
            complain = (scene_rep.warnings if c["status"] == "draft" else scene_rep.errors)
            if c["entry_scene"] not in ch_scenes:
                complain.append(f"{c['id']}: entry_scene {c['entry_scene']} не существует")
            for s in c.get("scene_order", []):
                if s not in ch_scenes:
                    complain.append(f"{c['id']}: scene_order: сцена {s} не существует")

    result.warnings.extend(scene_rep.warnings)
    if scene_rep.errors:
        raise CompileError(
            f"{len(scene_rep.errors)} ошибок компиляции сцен:\n" + "\n".join(scene_rep.errors)
        )

    # Реестр образов: фоны локаций + layeredimage из matrix и собранных слоёв (G11)
    img_rep = ImagesReport()
    images_out = emit_images(root, locations, char_docs, img_rep, _header(char_sources or [proj_src]))
    result.warnings.extend(img_rep.warnings)
    if img_rep.errors:
        raise CompileError(
            f"{len(img_rep.errors)} ошибок реестра образов:\n" + "\n".join(img_rep.errors)
        )

    outputs: dict[str, str] = {
        "registry/images.gen.rpy": images_out,
        "version.gen.rpy": _emit_version(project, git_sha(root), [proj_src]),
        "state/defaults.gen.rpy": _emit_defaults(project, var_docs, [proj_src] + var_sources),
        "registry/audio.gen.rpy": _emit_audio(audio_docs, audio_sources or [proj_src]),
        "registry/chapters.gen.rpy": sc.emit_chapter_registry(
            sorted(chapters, key=lambda c: c["id"]), _header([proj_src])
        ),
        "registry/scenes.gen.rpy": sc.emit_scene_registry(units, _header([proj_src])),
        "registry/characters.gen.rpy": sc.emit_characters(char_docs, _header(char_sources or [proj_src])),
        "registry/menus.gen.rpy": _emit_menus(menus, ui_strings, languages, [proj_src]),
        "registry/overrides.gen.rpy": _emit_overrides(renames, [renames_src]),
    }
    outputs.update(scene_outputs)
    if chapters:
        outputs["screens/chapter_select.gen.rpy"] = sc.emit_chapter_select(_header([proj_src]))

    old_manifest_path = gen / MANIFEST_NAME
    old_outputs: set[str] = set()
    if old_manifest_path.is_file():
        try:
            old_outputs = set(json.loads(old_manifest_path.read_text(encoding="utf-8"))["outputs"])
        except Exception:
            pass

    # Режим --check (G1): вычислить выходы в память, сравнить с диском, НИЧЕГО не писать.
    if check:
        for rel, text in sorted(outputs.items()):
            path = gen / rel
            if not path.is_file() or path.read_bytes() != text.encode("utf-8"):
                result.stale.append(rel)
        for orphan in sorted(old_outputs - set(outputs)):
            if (gen / orphan).is_file():
                result.stale.append(f"{orphan} (осиротел)")
        return result

    # Точечная очистка (G6): осиротевшие выходы прошлого манифеста + их .rpyc.
    for orphan in sorted(old_outputs - set(outputs)):
        for path in (gen / orphan, (gen / orphan).with_suffix(".rpyc")):
            if path.is_file():
                path.unlink()
                result.deleted.append(path.relative_to(gen).as_posix())

    # Запись: неизменённые файлы не трогаются байтово (G6).
    out_hashes: dict[str, str] = {}
    for rel, text in sorted(outputs.items()):
        data = text.encode("utf-8")
        out_hashes[rel] = _b3(data)
        path = gen / rel
        if path.is_file() and path.read_bytes() == data:
            result.skipped.append(rel)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        result.written.append(rel)

    manifest = {
        "schema": "gen_manifest@1",
        "tool": __version__,
        "inputs": dict(sorted(inputs.items())),
        "outputs": out_hashes,
    }
    gen.mkdir(parents=True, exist_ok=True)
    old_manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=1, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return result
