"""vn content compile — Content Compiler.

Фаза 0: version, defaults (named stores), audio, overrides, менюшный реестр, манифест,
инкрементальность и точечная очистка (G6).
Фаза 1: главы и сцены — авторские scene.rpy разбираются парсером Ren'Py через build-bridge
(G24, analyze.py), валидируется контракт C2, эмитится label-обвязка, Chapter/Scene Registry,
персонажи, экран выбора глав.

Контракты генерата:
- каждый файл несёт заголовок AUTO-GENERATED + blake3 источников;
- неизменённые файлы не перезаписываются байтово (иначе Ren'Py перекомпилирует все .rpyc);
- очистка — только по диффу манифестов: удаляются осиротевшие пары .rpy+.rpyc.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path

import blake3

from .. import __version__
from ..repo import git_sha, load_project, load_yaml
from . import scenes as sc
from .analyze import AnalyzeError, analyze_scene_files
from .images import ImagesReport, emit_images, load_locations

MANIFEST_NAME = "manifest.json"
CHAPTER_DIR_RE = re.compile(r"^ch(\d{2})_([a-z][a-z0-9_]{2,30})$")
SCENE_YAML_RE = re.compile(r"^s(\d{3})_([a-z][a-z0-9_]{2,40})\.scene\.yaml$")


class CompileError(RuntimeError):
    pass


@dataclass
class CompileResult:
    written: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)
    deleted: list[str] = field(default_factory=list)
    stale: list[str] = field(default_factory=list)      # только в режиме check
    warnings: list[str] = field(default_factory=list)


def _b3(data: bytes) -> str:
    return blake3.blake3(data).hexdigest()


def _b3_file(path: Path) -> str:
    return _b3(path.read_bytes())


def _header(sources: list[tuple[str, str]]) -> str:
    lines = [
        "# " + "═" * 62,
        f"# AUTO-GENERATED by vn content compile (vn {__version__})",
    ]
    for rel, digest in sources:
        lines.append(f"# source: {rel}  blake3:{digest[:16]}")
    lines += [
        "# НЕ РЕДАКТИРОВАТЬ. Правки перезапишутся. Меняйте источник.",
        "# " + "═" * 62,
        "",
    ]
    return "\n".join(lines)


def _py_literal(value) -> str:
    """YAML-значение -> литерал Python/Ren'Py (в сейве только простые типы, G5)."""
    if isinstance(value, (str, int, float, bool)) or value is None:
        return repr(value)
    if isinstance(value, (list, dict)):
        return repr(value)
    raise CompileError(f"недопустимый тип default-значения: {type(value).__name__}")


# ── Эмиттеры фазы 0 ───────────────────────────────────────────────────────────

# Git sha внутри config.version — метаданные СБОРКИ, а не контента: он меняется на
# каждом коммите, даже если content/ не тронут. Сравнивая его буквально, --check
# краснел после любого коммита и переставал отвечать на свой единственный вопрос —
# «генерат отстал от источников?». Semver при этом сравнивается как есть: забытая
# пересборка после бампа project.yaml:version обязана ловиться.
_VERSION_SHA_RE = re.compile(rb'(define config\.version = "\d+\.\d+\.\d+)\+[0-9a-f]{4,40}"')


def _stale_key(rel: str, data: bytes) -> bytes:
    """Форма выхода для сравнения свежести: без волатильных метаданных сборки."""
    if rel == "version.gen.rpy":
        return _VERSION_SHA_RE.sub(rb'\1+<sha>"', data)
    return data


def _emit_version(project: dict, sha: str, sources) -> str:
    version = f"{project['version']}+{sha}"
    return _header(sources) + (
        "init offset = -900\n\n"
        f'define config.version = "{version}"\n'
    )


def _emit_render(root: Path, sources) -> str:
    """Render-профиль -> config движка (ADR-0012).

    Раньше `config.image_cache_size_mb` не задавался нигде и жил на дефолте SDK
    (400), то есть потолок памяти сцены был случайным числом, а не решением
    проекта. Теперь он выводится из project.yaml: render и проверяется моделью
    памяти (vn assets memory) на тех же данных.

    init offset = -950: раньше версии и любых контентных define — config должен
    быть установлен до того, как движок начнёт создавать кэш образов."""
    from ..assets.render_config import load_render_config

    cfg = load_render_config(root)
    return _header(sources) + (
        "init offset = -950\n\n"
        "# Пиксельный лимит кэша образов: cache_limit = value * 1024 * 1024 // 4\n"
        "# (renpy/display/im.py: Cache.init). Источник — project.yaml: render.\n"
        f"define config.image_cache_size_mb = {cfg.image_cache_mb}\n\n"
        "# Автоподбор оверсэмпл-вариантов (<name>@2/@4) под физический экран.\n"
        "# Фиксируем явно: от него зависит, увидит ли игрок 4K-ассеты вообще.\n"
        "# Это ПОТОЛОК СБОРКИ (project.yaml: render.max_oversampling); настройка\n"
        "# качества игрока может опустить его ниже (00_core/095_quality.rpy).\n"
        f"define config.automatic_oversampling = {cfg.max_oversampling}\n\n"
        "# Потолок сборки для настройки качества (не трогать руками).\n"
        f"define vn_build_max_oversampling = {cfg.max_oversampling}\n"
    )


def _emit_platform(project: dict, packs: dict[str, dict], sources) -> str:
    """Платформенный конфиг (ADR-0014): App ID и карта DLC-владения — данные.

    config.steam_appid обязан задаваться define-стейтментом: движок собирает
    define config.* ДО ранних init (steam_init работает на init -1499 —
    раньше любого пользовательского кода). appid = None => движок сам удаляет
    steam_appid.txt и не трогает Steam. Рантайм-провайдеры подключает
    framework/00_core/035_platform.rpy — единственная точка касания Steam."""
    steam = (project.get("platform") or {}).get("steam") or {}
    appid = steam.get("appid")
    dlc = {pid: m["steam_dlc_appid"] for pid, m in sorted(packs.items())
           if m.get("steam_dlc_appid")}
    return _header(sources) + (
        "# App ID публичен (не секрет). None = Steam выключен: движок пропускает\n"
        "# инициализацию и удаляет steam_appid.txt (защита от чужого appid).\n"
        f"define config.steam_appid = {appid!r}\n\n"
        "# pack_id -> Steam DLC App ID: владение проверяет платформенный провайдер\n"
        "# (vn_platform), паки без маппинга гейтятся только установленностью (G9).\n"
        f"define VN_STEAM_DLC = {dlc!r}\n"
    )


def _emit_defaults(project: dict, var_docs: list[tuple[str, dict]], sources) -> str:
    stores = sorted({doc["store"] for _, doc in var_docs if doc["store"] != "persistent"})
    out = [_header(sources)]
    if stores:
        out.append("# Создание named stores (шкала init-приоритетов — C8/ADR-0003)")
        for store in stores:
            out.append(f"init -980 python in {store}:\n    pass\n")
    for rel, doc in sorted(var_docs):
        store = doc["store"]
        for name, spec in sorted((doc.get("vars") or {}).items()):
            if store == "persistent" and not name.startswith("vn_"):
                # C9: плоская модель persistent.vn_* — без префикса имя запрещено.
                raise CompileError(
                    f"{rel}: persistent-переменная {name!r} обязана начинаться с vn_ (C9)"
                )
            out.append(f"default {store}.{name} = {_py_literal(spec['default'])}")
    out.append("")
    out.append("# Версия схемы сейва (G5): vn_save_schema едет в сейв,")
    out.append("# vn_build_save_schema — константа текущей сборки (сравнение в label after_load).")
    out.append(f"default vn_save_schema = {project['save_schema']}")
    out.append(f"define vn_build_save_schema = {project['save_schema']}")
    return "\n".join(out) + "\n"


def _emit_achievements(ach_docs: list[tuple[str, dict]], sources) -> str:
    """Реестр достижений (achievements@1): данные для рантайма vn_ach.
    Привязка — к стабильным якорям (scene/beat/var), не к тексту сцен."""
    rows: dict[str, dict] = {}
    for _rel, doc in sorted(ach_docs):
        for aid, spec in sorted((doc.get("achievements") or {}).items()):
            trigger = dict(spec["trigger"])
            if "var" in trigger and "equals" not in trigger:
                trigger["equals"] = True
            rows[aid] = {
                "name_key": spec["name_key"],
                "desc_key": spec.get("desc_key"),
                "hidden": bool(spec.get("hidden", False)),
                "nsfw": bool(spec.get("nsfw", False)),
                "pack": spec.get("pack", "core"),
                "trigger": trigger,
            }
    return _header(sources) + (
        "init offset = -100\n\n"
        "# Achievement Registry (achievements@1): читается store vn_ach\n"
        "# (framework/00_core/080_achievements.rpy). Выдача — по стабильным якорям.\n"
        f"define VN_ACHIEVEMENTS = {rows!r}\n"
    )


GALLERY_THUMB_SUFFIX = ".thumb.webp"


def _gallery_asset_paths(asset_id: str) -> tuple[str, str]:
    """Логический id ассета -> (путь для движка, имя образа через пробелы)."""
    ext = ".webm" if asset_id.startswith("mov/") else ".webp"
    return f"assets/{asset_id}{ext}", asset_id.replace("/", " ")


def _asset_history(renames: dict) -> dict[str, list[str]]:
    """Текущий логический id ассета -> его исторические имена.

    renames.assets ведётся как «старый -> новый» и может быть цепочкой
    (a -> b -> c). Разворачиваем в «конечный -> все предки», чтобы рантайм
    галереи мог засчитать кадр, показанный игроку под старым именем."""
    forward = dict(renames.get("assets") or {})
    history: dict[str, list[str]] = {}
    for old in forward:
        current, seen = old, {old}
        while current in forward and forward[current] not in seen:
            current = forward[current]
            seen.add(current)
        history.setdefault(current, []).append(old)
    return {k: sorted(v) for k, v in history.items()}


def _emit_gallery(root: Path, gal_docs: list[tuple[str, dict]], known_scenes: set[str],
                  chapter_ids: set[str], var_registry: set[str],
                  ui_strings: dict, rep: CompileResult, errors: list[str],
                  sources, renames: dict | None = None) -> str:
    """Реестр галереи (gallery@1) + валидация: битые ассеты/превью/категории/якоря
    ловятся до запуска игры. UI получает только данные — ни списка элементов в
    коде, ни логики разблокировки."""
    assets_dir = root / "game" / "assets"
    # Зона ассетов производная (G4): её может не быть вовсе — например, при
    # vn content compile без предшествующей сборки. Тогда существование файлов
    # не проверяем (это не ошибка деклараций), но честно предупреждаем; при
    # собранной зоне проверка строгая. Тот же приём, что у эмиттера образов.
    assets_built = assets_dir.is_dir()
    if gal_docs and not assets_built:
        rep.warnings.append(
            "галерея: game/assets не собран — ссылки на ассеты и превью не "
            "проверены (выполните vn build)")

    categories: dict[str, dict] = {}
    items: dict[str, dict] = {}
    used_assets: set[str] = set()
    history = _asset_history(renames or {})

    for rel, doc in sorted(gal_docs):
        for cid, spec in (doc.get("categories") or {}).items():
            if cid in categories:
                errors.append(f"{rel}: категория {cid!r} объявлена дважды")
                continue
            categories[cid] = {
                "title_key": spec["title_key"],
                "order": int(spec.get("order", 100)),
                "nsfw": bool(spec.get("nsfw", False)),
            }
        for gid, spec in (doc.get("items") or {}).items():
            if gid in items:
                errors.append(f"{rel}: элемент галереи {gid!r} объявлен дважды")
                continue
            items[gid] = dict(spec, _src=rel)

    for gid, spec in sorted(items.items()):
        rel = spec.pop("_src")
        cat = spec["category"]
        if cat not in categories:
            errors.append(f"{rel}: {gid}: категория {cat!r} не объявлена "
                          f"(есть: {', '.join(sorted(categories)) or 'ни одной'})")
        kind = spec["kind"]
        assets = [spec["asset"], *(spec.get("variants") or [])]
        for a in assets:
            used_assets.add(a)
            path, _name = _gallery_asset_paths(a)
            if assets_built and not (assets_dir / path[len("assets/"):]).is_file():
                errors.append(f"{rel}: {gid}: ассета {a} нет в game/assets "
                              f"(ожидался {path}) — прогоните vn build")
            if kind == "movie" and not a.startswith("mov/"):
                errors.append(f"{rel}: {gid}: kind: movie, но ассет {a} не из mov/")
            if kind == "image" and a.startswith("mov/"):
                errors.append(f"{rel}: {gid}: kind: image, но ассет {a} — видео")
        # Превью: для картинок берём из конвейера, для видео обязателен явный
        thumb = spec.get("thumb")
        if thumb:
            used_assets.add(thumb)
            tpath, _n = _gallery_asset_paths(thumb)
            if assets_built and not (assets_dir / tpath[len("assets/"):]).is_file():
                errors.append(f"{rel}: {gid}: превью {thumb} нет в game/assets")
            # Даже у явного превью в сетку идёт thumb-вариант, если конвейер его
            # сделал: полноразмерные кадры в сетке — это лишние мегабайты текстур.
            small = f"assets/{thumb}{GALLERY_THUMB_SUFFIX}"
            resolved_thumb = small if (assets_dir / small[len("assets/"):]).is_file() \
                else tpath
        elif kind == "image":
            cand = f"assets/{spec['asset']}{GALLERY_THUMB_SUFFIX}"
            if assets_built and not (assets_dir / cand[len("assets/"):]).is_file():
                rep.warnings.append(
                    f"{rel}: {gid}: нет превью {cand} — сетка будет крутить "
                    f"полноразмерный кадр (ожидается png2webp_cg_thumb)")
                cand = _gallery_asset_paths(spec["asset"])[0]
            resolved_thumb = cand
        else:
            # Постер-кадр конвейер делает сам (ADR-0012): ручной thumb у видео
            # больше не обязателен, а заглушка в сетке — редкое исключение.
            from ..assets.pipeline import POSTER_SUFFIX

            cand = f"assets/{spec['asset']}{POSTER_SUFFIX}"
            if not assets_built or (assets_dir / cand[len("assets/"):]).is_file():
                resolved_thumb = cand
            else:
                rep.warnings.append(f"{rel}: {gid}: нет постер-кадра {cand} — "
                                    f"в сетке будет заглушка")
                resolved_thumb = None

        unlock = dict(spec["unlock"])
        if "seen_image" in unlock and kind != "image":
            errors.append(f"{rel}: {gid}: unlock.seen_image работает только "
                          f"для kind: image (движковый _seen_images)")
        if "scene" in unlock and known_scenes and unlock["scene"] not in known_scenes:
            errors.append(f"{rel}: {gid}: unlock.scene {unlock['scene']} — такой сцены нет")
        if "chapter_done" in unlock and chapter_ids \
                and unlock["chapter_done"] not in chapter_ids:
            errors.append(f"{rel}: {gid}: unlock.chapter_done "
                          f"{unlock['chapter_done']} — такой главы нет")
        if "var" in unlock:
            if var_registry and unlock["var"] not in var_registry:
                errors.append(f"{rel}: {gid}: unlock.var {unlock['var']} нет "
                              f"в Variable Registry")
            unlock.setdefault("equals", True)
        for key in ("title_key", "desc_key"):
            k = spec.get(key)
            if k and ui_strings and k not in ui_strings:
                rep.warnings.append(f"{rel}: {gid}: {key} {k!r} нет в "
                                    f"content/ui/strings.yaml — покажется сырой ключ")

        full_path, image_name = _gallery_asset_paths(spec["asset"])
        # Исторические имена образа: игрок мог увидеть кадр под прошлым id, и
        # переименование файла не должно стирать ему открытую CG (ADR-0012).
        past = [_gallery_asset_paths(old)[1]
                for old in history.get(spec["asset"], [])]
        items[gid] = {
            "category": cat,
            "kind": kind,
            "asset": full_path,
            "image_name": image_name,
            "image_name_history": past,
            "variants": [_gallery_asset_paths(v)[0] for v in (spec.get("variants") or [])],
            "thumb": resolved_thumb,
            "title_key": spec["title_key"],
            "desc_key": spec.get("desc_key"),
            "chapter": spec.get("chapter"),
            "characters": list(spec.get("characters") or []),
            "order": int(spec.get("order", 100)),
            "nsfw": bool(spec.get("nsfw", False)),
            "pack": spec.get("pack", "core"),
            "unlock": unlock,
        }

    # Осиротевшие CG: ассет собран, но в галерее не объявлен (арт готовится
    # раньше сцен — это warning, не ошибка; §2.12 про orphan-политику).
    from ..assets.pipeline import variant_scale

    cg_root = assets_dir / "cg"
    if cg_root.is_dir():
        for f in sorted(cg_root.rglob("*.webp")):
            if f.name.endswith(GALLERY_THUMB_SUFFIX) or variant_scale(f.stem) != 1:
                continue
            logical = "cg/" + f.relative_to(cg_root).as_posix()[: -len(".webp")]
            if logical not in used_assets:
                rep.warnings.append(
                    f"{logical}: CG собран, но не объявлен в галерее "
                    f"(content/gallery/*.gallery.yaml) — игрок его не увидит в галерее")

    cats = {cid: categories[cid] for cid in
            sorted(categories, key=lambda c: (categories[c]["order"], c))}
    return _header(sources) + (
        "init offset = -100\n\n"
        "# Gallery Registry (gallery@1): читается store vn_gal\n"
        "# (framework/00_core/090_gallery.rpy) и экранами галереи. Категории и\n"
        "# элементы — данные: UI не содержит ни списка, ни логики разблокировки.\n"
        f"define VN_GALLERY_CATEGORIES = {cats!r}\n\n"
        f"define VN_GALLERY = {items!r}\n"
    )


def _emit_ui_frames(panels: dict, sources) -> str:
    """Frame-образы генерируемых UI-панелей (ADR-0009): вёрстка ссылается на
    vn_frame_<id>, пиксели и пути остаются в конвейере."""
    from ..assets.ui import emit_frames

    return emit_frames(panels, _header(sources))


def _emit_audio(audio_docs: list[tuple[str, dict]], sources) -> str:
    out = [_header(sources), "init offset = 500\n"]
    n = 0
    for rel, doc in sorted(audio_docs):
        for track_id, spec in sorted((doc.get("tracks") or {}).items()):
            file = spec["file"]
            # Точка лупа — штатным префиксом partial-playback ("<loop N>file"):
            # движок сам зацикливает с указанной секунды, кода в рантайме ноль.
            if spec.get("loop_start"):
                file = f"<loop {spec['loop_start']}>{file}"
            out.append(f'define audio.{track_id} = "{file}"')
            n += 1
    if not n:
        out.append("# Треки не объявлены (content/audio/*.yaml пусты).")
    return "\n".join(out) + "\n"


def _emit_menus(menus: dict, strings: dict, source_lang: dict, sources) -> str:
    return _header(sources) + (
        "init offset = -100\n\n"
        "# Реестр choice-id (G8/C1): исходные подписи пунктов по id (источник —\n"
        "# loc/ledger/, vn loc keys). Валидация/QA; переводы пунктов рантайм берёт\n"
        "# из VN_MENUS_TL (vn_loc.choice_text).\n"
        f"define VN_MENUS = {menus!r}\n\n"
        "# Переводы наполняют tl/<lang>/common.rpy на init 600 (vn loc import).\n"
        "define VN_MENUS_TL = {}\n"
        "define VN_STRINGS_TL = {}\n\n"
        "# UI/мета-строки (content/ui/strings.yaml): vn_loc.t(key) -> текст/перевод.\n"
        f"define VN_STRINGS = {strings!r}\n\n"
        "# Исходный язык проекта (loc/loc.yaml, в Ren'Py — language=None).\n"
        "# Списка языков здесь НЕТ: Language Registry (store vn_lang) сканирует\n"
        "# game/tl/*/language.json в рантайме (ADR-0005).\n"
        f"define VN_SOURCE_LANG = {source_lang!r}\n"
    )


def _emit_snapshot(var_docs: list[tuple[str, dict]], sources) -> str:
    pairs = []
    stores = set()
    for _rel, doc in sorted(var_docs):
        if doc["store"] == "persistent":
            continue    # persistent живёт своим механизмом, в снапшот не входит
        stores.add(doc["store"])
        for name in sorted(doc.get("vars") or {}):
            pairs.append((doc["store"], name))
    return _header(sources) + (
        "init -970 python in vn_state:\n"
        "    # Единый маппинг stores<->dict (G5): миграции в игре и внешний тулинг\n"
        "    # исполняют одну и ту же цепочку над этим снапшотом.\n"
        "    # snapshot() читает ВСЕ переменные управляемых stores (retired-переменные\n"
        "    # старых сейвов видимы миграциям), apply — только объявленные.\n"
        f"    SNAPSHOT_VARS = {tuple(pairs)!r}\n"
        f"    SNAPSHOT_STORES = {tuple(sorted(stores))!r}\n"
    )


def _emit_migrations(migrations: list[tuple[int, str, str]], sources) -> str:
    out = [_header(sources)]
    out.append("init -960 python in vn_state:")
    if not migrations:
        out.append("    pass    # миграций нет (save_schema == 1)")
        return "\n".join(out) + "\n"
    out.append("    def _vn_load_migration(number, source, filename):")
    out.append("        ns = {}")
    out.append('        exec(compile(source, filename, "exec"), ns)')
    out.append('        if "migrate" not in ns:')
    out.append('            raise Exception("%s: нет функции migrate(state)" % filename)')
    out.append("        MIGRATIONS.append((number, ns[\"migrate\"]))")
    out.append("")
    for number, filename, source in migrations:
        out.append(f"    _vn_load_migration({number}, {source!r}, {filename!r})")
    out.append("    MIGRATIONS.sort(key=lambda t: t[0])")
    return "\n".join(out) + "\n"


def _collect_migrations(root: Path, src, project: dict, errors: list[str]):
    """content/migrations/NNNN_slug.py: номер = целевая schema; цепочка непрерывна
    от 2 до save_schema; каждый номер зарезервирован в registry.yaml (G5)."""
    mig_re = re.compile(r"^(\d{4})_([a-z][a-z0-9_]+)\.py$")
    mig_dir = root / "content" / "migrations"
    reserved: dict[int, dict] = {}
    reg_path = mig_dir / "registry.yaml"
    if reg_path.is_file():
        rel, _d = src(reg_path)
        for r in load_yaml(reg_path).get("reserved") or []:
            reserved[r["number"]] = r
    migrations: list[tuple[int, str, str]] = []
    for f in sorted(mig_dir.glob("*.py")) if mig_dir.is_dir() else []:
        m = mig_re.match(f.name)
        if not m:
            errors.append(f"content/migrations/{f.name}: имя вне конвенции NNNN_slug.py")
            continue
        number = int(m.group(1))
        rel, _d = src(f)
        if number not in reserved:
            errors.append(
                f"{rel}: номер {number} не зарезервирован в content/migrations/registry.yaml "
                f"(параллельные ветки получат конфликт номеров, G5)"
            )
        migrations.append((number, f.name, f.read_text(encoding="utf-8")))
    migrations.sort()
    numbers = [n for n, _f, _s in migrations]
    expected = list(range(2, project["save_schema"] + 1))
    if numbers != expected:
        errors.append(
            f"content/migrations: цепочка {numbers} != ожидаемой {expected} "
            f"(номер миграции = целевая save_schema; дыры и лишние номера запрещены)"
        )
    return migrations


def _emit_overrides(renames: dict, sources,
                    registry_scenes: list[str] | None = None,
                    known_scenes: set[str] | None = None) -> str:
    out = [_header(sources)]
    scene_renames: dict = renames.get("scenes") or {}
    deleted: dict = renames.get("deleted_scenes") or {}
    labels: dict = renames.get("labels") or {}
    overrides = dict(scene_renames)
    overrides.update({old: spec["fallback"] for old, spec in deleted.items()})
    overrides.update(labels)
    out.append("init -100 python:")
    out.append("    # update, а не define: DLC-паки могут дополнять карту (C12).")
    out.append(f"    config.label_overrides.update({overrides!r})")
    out.append("")
    if overrides:
        out.append("# Shim-метки (G7): дают rollback-логу и call-стеку точку опоры,")
        out.append("# которой label_overrides не даёт. Перед jump — размотка стека:")
        out.append("# сейв со старым id и грязным call-стеком не должен тащить лишние кадры.")
        for old, new in sorted(overrides.items()):
            out.append(f"label {old}:\n    $ vn.unwind_call_stack()\n    jump {new}\n")
    else:
        out.append("# Переименований нет — shim-метки не требуются.")

    # Shim-метки для выпущенных id, отсутствующих в ЭТОЙ сборке (G7, раздел 3.8):
    # сейв внутри неустановленного пака/эпизода без них падает ScriptError прямо
    # в crash-экран. С ними игрок получает объяснение и выбор действия.
    missing = sorted(set(registry_scenes or []) - (known_scenes or set())
                     - set(overrides))
    if missing:
        out.append("# Выпущенные сцены вне этой сборки (id_registry): маршрут на")
        out.append("# «контент недоступен» вместо ScriptError у игрока.")
        for scene_id in missing:
            out.append(
                f"label {scene_id}:\n"
                f"    $ vn.unwind_call_stack()\n"
                f'    $ vn_unavailable_reason = "missing_content"\n'
                f"    jump vn_scene_unavailable\n")
    return "\n".join(out) + "\n"


# ── Сбор контента фазы 1 ─────────────────────────────────────────────────────

# API-уровень фасада vn.* (зеркало framework/00_core/030_flow.rpy: API_LEVEL);
# манифесты паков требуют диапазон api_level — несовместимый пак отключается (G9).
VN_API_LEVEL = 1


def _collect_packs(root: Path, src, registry, errors: list[str]) -> dict[str, dict]:
    """packs/<id>/manifest.yaml: валидация + api_level против фасада (G9/G10)."""
    packs: dict[str, dict] = {}
    packs_dir = root / "packs"
    if not packs_dir.is_dir():
        return packs
    for d in sorted(p for p in packs_dir.iterdir() if p.is_dir()):
        mf = d / "manifest.yaml"
        if not mf.is_file():
            errors.append(f"packs/{d.name}: нет manifest.yaml (pack_manifest@1)")
            continue
        rel, _digest = src(mf)
        manifest = load_yaml(mf)
        m_errs = registry.validate(manifest, rel)
        if m_errs:
            errors.extend(m_errs)
            continue
        if manifest["id"] != d.name:
            errors.append(f"{rel}: id ({manifest['id']}) != имени папки ({d.name})")
            continue
        api = manifest["api_level"]
        if not (api["min"] <= VN_API_LEVEL < api["below"]):
            errors.append(
                f"{rel}: api_level [{api['min']}, {api['below']}) несовместим с фасадом "
                f"vn.* (текущий {VN_API_LEVEL}) — пак не собирается (G9)"
            )
            continue
        core_req = (manifest.get("requires") or {}).get("core")
        if core_req and not _semver_in_range(_current_version(root), core_req):
            errors.append(
                f"{rel}: requires.core {core_req!r} несовместим с версией ядра "
                f"{_current_version(root)} — пак не собирается (G9)"
            )
            continue
        packs[manifest["id"]] = manifest
    return packs


def _current_version(root: Path) -> str:
    return load_project(root)["version"]


def _semver_in_range(version: str, spec: str) -> bool:
    """Диапазоны вида '>=0.1.0 <1' / '==1.2.3' (пробел = И). Неизвестный оператор
    трактуется строго (False) — совместимость не угадывается."""
    def parse(v: str):
        return tuple(int(x) for x in (v.split(".") + ["0", "0"])[:3])

    v = parse(version)
    for clause in spec.split():
        for op in (">=", "<=", "==", "<", ">"):
            if clause.startswith(op):
                bound = parse(clause[len(op):])
                ok = {"<": v < bound, "<=": v <= bound, ">": v > bound,
                      ">=": v >= bound, "==": v == bound}[op]
                if not ok:
                    return False
                break
        else:
            return False
    return True


def _collect_chapters(root: Path, src, registry, errors: list[str],
                      packs: dict[str, dict] | None = None):
    """Главы ядра (content/chapters/) и паков (packs/<id>/chapters/): принадлежность
    паку — по расположению (C10), поле chapter.yaml pack: не существует."""
    chapters: list[dict] = []
    units: list[sc.SceneUnit] = []
    voice_docs: list[tuple[str, str, str, dict]] = []    # (chapter, lang, rel, doc)
    shots_docs: list[tuple[str, str, dict]] = []        # (chapter, rel, doc)
    zones = [("core", root / "content" / "chapters")]
    for pack_id in sorted(packs or {}):
        zones.append((pack_id, root / "packs" / pack_id / "chapters"))
    for pack_id, chapters_dir in zones:
        if not chapters_dir.is_dir():
            continue
        for d in sorted(p for p in chapters_dir.iterdir() if p.is_dir()):
            _collect_chapter_dir(root, src, registry, errors, chapters, units, d, pack_id)
            _collect_voice_dir(root, src, registry, errors, voice_docs, d)
            _collect_shots_dir(root, src, registry, errors, shots_docs, d)
    return chapters, units, voice_docs, shots_docs


SHOTS_YAML_RE = re.compile(r"^(s\d{3})\.shots\.yaml$")


def _collect_shots_dir(root: Path, src, registry, errors, shots_docs, d):
    """Декларации послойных шотов (shots@1, ADR-0013): schema + инварианты файла.
    Существование сцены и переменных гардероба сверяется позже, когда собраны
    сцены и Variable Registry."""
    sdir = d / "shots"
    if not sdir.is_dir():
        return
    ch_id = d.name[:4]
    for f in sorted(sdir.glob("*.shots.yaml")):
        rel, _digest = src(f)
        m = SHOTS_YAML_RE.match(f.name)
        if not m:
            errors.append(f"{rel}: имя файла вне конвенции sNNN.shots.yaml")
            continue
        doc = load_yaml(f)
        s_errs = registry.validate(doc, rel)
        if s_errs:
            errors.extend(s_errs)
            continue
        if doc["scene"] != m.group(1):
            errors.append(f"{rel}: scene ({doc['scene']}) != имени файла ({m.group(1)})")
            continue
        bad = False
        for shot_id, spec in sorted((doc.get("shots") or {}).items()):
            layers = spec["layers"]
            if layers.get("env", {}).get("variants"):
                errors.append(
                    f"{rel}: {shot_id}: у подложки env вариантов не бывает — "
                    f"вариативная среда = отдельный шот")
                bad = True
            if sorted(spec["order"]) != sorted(layers):
                errors.append(
                    f"{rel}: {shot_id}: order {spec['order']} != слоям "
                    f"{sorted(layers)} — z-порядок обязан перечислить каждый слой "
                    f"ровно один раз")
                bad = True
        if not bad:
            shots_docs.append((ch_id, rel, doc))


def _collect_voice_dir(root: Path, src, registry, errors, voice_docs, d):
    """Voice-манифесты главы (voice@1, C5): schema + инварианты пути.
    Сверка line_id с фактическими say-id сцен — позже, когда есть AST."""
    from ..voice import LANG_RE, MANIFEST_SUFFIX

    vdir = d / "voice"
    if not vdir.is_dir():
        return
    ch_id = d.name[:4]
    for f in sorted(vdir.glob("*" + MANIFEST_SUFFIX)):
        rel, _digest = src(f)
        lang = f.name[: -len(MANIFEST_SUFFIX)]
        doc = load_yaml(f)
        v_errs = registry.validate(doc, rel)
        if v_errs:
            errors.extend(v_errs)
            continue
        if not LANG_RE.match(lang):
            errors.append(f"{rel}: имя файла {lang!r} — не код языка "
                          f"(ожидается <lang>{MANIFEST_SUFFIX})")
            continue
        if doc["lang"] != lang:
            errors.append(f"{rel}: lang ({doc['lang']}) != имени файла ({lang})")
            continue
        if doc["chapter"] != ch_id:
            errors.append(f"{rel}: chapter ({doc['chapter']}) != главе каталога ({ch_id})")
            continue
        bad = sorted(lid for lid in (doc.get("lines") or {})
                     if not lid.startswith(ch_id + "_"))
        if bad:
            errors.extend(f"{rel}: {lid}: реплика чужой главы в манифесте {ch_id}"
                          for lid in bad)
            continue
        voice_docs.append((ch_id, lang, rel, doc))


def _collect_chapter_dir(root: Path, src, registry, errors, chapters, units, d, pack_id):
    zone = d.parent.relative_to(root).as_posix()
    m = CHAPTER_DIR_RE.match(d.name)
    if not m:
        errors.append(f"{zone}/{d.name}: имя папки вне конвенции (naming.md)")
        return
    ch_id = f"ch{m.group(1)}"
    if any(c["id"] == ch_id for c in chapters):
        errors.append(f"{zone}/{d.name}: id {ch_id} уже занят другой главой (ядро/пак)")
        return
    ch_yaml = d / "chapter.yaml"
    if not ch_yaml.is_file():
        errors.append(f"{zone}/{d.name}: нет chapter.yaml")
        return
    rel, _digest = src(ch_yaml)
    meta = load_yaml(ch_yaml)
    errs = registry.validate(meta, rel)
    if errs:
        errors.extend(errs)
        return
    if meta["id"] != ch_id:
        errors.append(f"{rel}: id ({meta['id']}) != префиксу папки ({ch_id}) — "
                      f"entry_label разошёлся бы с метками сцен")
        return
    meta["pack"] = pack_id    # принадлежность по расположению (C10)
    chapters.append(meta)

    scenes_dir = d / "scenes"
    seen_short: dict[str, str] = {}
    if not scenes_dir.is_dir():
        return
    for f in sorted(scenes_dir.glob("*.scene.yaml")):
        sm = SCENE_YAML_RE.match(f.name)
        if not sm:
            errors.append(f"{rel}: файл сцены вне конвенции: {f.name}")
            continue
        if f"s{sm.group(1)}" in seen_short:
            errors.append(
                f"{zone}/{d.name}/scenes: дубликат id s{sm.group(1)}: "
                f"{seen_short[f's{sm.group(1)}']} и {f.name} — одна из сцен молча "
                f"выпала бы из генерата"
            )
            continue
        seen_short[f"s{sm.group(1)}"] = f.name
        yaml_rel, _d1 = src(f)
        smeta = load_yaml(f)
        s_errs = registry.validate(smeta, yaml_rel)
        if s_errs:
            errors.extend(s_errs)
            continue
        rpy = f.parent / (f.name[: -len(".yaml")] + ".rpy")
        if not rpy.is_file():
            errors.append(f"{yaml_rel}: нет парного .scene.rpy (G3)")
            continue
        rpy_rel, _d2 = src(rpy)
        short_id = f"s{sm.group(1)}"
        units.append(sc.SceneUnit(
            full_id=f"{ch_id}_{short_id}",
            chapter_id=ch_id,
            short_id=short_id,
            yaml_rel=yaml_rel,
            rpy_rel=rpy_rel,
            meta=smeta,
            rpy_text=rpy.read_text(encoding="utf-8"),
            analysis={},
        ))


# ── Оркестрация ───────────────────────────────────────────────────────────────

def compile_content(root: Path, out_dir: Path | None = None, check: bool = False) -> CompileResult:
    gen = out_dir if out_dir is not None else root / "game" / "generated"

    from ..schemas import SchemaRegistry
    registry = SchemaRegistry(root / "tools" / "schemas")
    project = load_project(root)
    proj_errors = registry.validate(project, "project.yaml")
    if proj_errors:
        raise CompileError("невалидный project.yaml: " + "; ".join(proj_errors))

    inputs: dict[str, str] = {}

    def src(path: Path) -> tuple[str, str]:
        if not path.is_file():
            raise CompileError(
                f"обязательный вход компилятора отсутствует: {path.relative_to(root).as_posix()} "
                f"(vn content lint обязан это ловить — если нет, это баг линтера)"
            )
        rel = path.relative_to(root).as_posix()
        digest = _b3_file(path)
        inputs[rel] = digest
        return rel, digest

    proj_src = src(root / "project.yaml")
    result = CompileResult()
    errors: list[str] = []

    # Переменные: глобальные + главные (chNN)
    var_docs, var_sources = [], []
    variables_dir = root / "content" / "variables"
    if variables_dir.is_dir():
        for f in sorted(variables_dir.glob("*.vars.yaml")):
            var_sources.append(src(f))
            var_docs.append((f.name, load_yaml(f)))
    for f in sorted((root / "content" / "chapters").glob("*/vars.yaml")):
        rel, _d = src(f)
        var_docs.append((rel, load_yaml(f)))
        var_sources.append((rel, inputs[rel]))

    # Достижения (achievements@1): опциональная зона content/achievements/
    ach_docs, ach_sources = [], []
    ach_dir = root / "content" / "achievements"
    if ach_dir.is_dir():
        for f in sorted(ach_dir.glob("*.yaml")):
            rel, _d = src(f)
            doc = load_yaml(f)
            a_errs = registry.validate(doc, rel)
            if a_errs:
                errors.extend(a_errs)
                continue
            ach_docs.append((rel, doc))
            ach_sources.append((rel, inputs[rel]))

    # Галерея (gallery@1, ADR-0010)
    gal_docs, gal_sources = [], []
    gal_dir = root / "content" / "gallery"
    if gal_dir.is_dir():
        for f in sorted(gal_dir.glob("*.yaml")):
            rel, _d = src(f)
            doc = load_yaml(f)
            g_errs = registry.validate(doc, rel)
            if g_errs:
                errors.extend(g_errs)
                continue
            gal_docs.append((rel, doc))
            gal_sources.append((rel, inputs[rel]))

    # Аудио: единый реестр треков с kind — id глобально уникален между kind'ами,
    # иначе define audio.<id> одного файла молча перезаписал бы другой.
    audio_docs, audio_sources = [], []
    audio_dir = root / "content" / "audio"
    if audio_dir.is_dir():
        for f in sorted(audio_dir.glob("*.yaml")):
            audio_sources.append(src(f))
            audio_docs.append((f.name, load_yaml(f)))
    audio_tracks: dict[str, dict] = {}
    for rel_name, doc in sorted(audio_docs):
        for tid, spec in sorted((doc.get("tracks") or {}).items()):
            if tid in audio_tracks:
                errors.append(
                    f"content/audio/{rel_name}: трек {tid!r} уже объявлен как "
                    f"{audio_tracks[tid]['kind']} — define audio.{tid} перезаписался бы молча"
                )
                continue
            audio_tracks[tid] = dict(spec, kind=doc.get("kind"))

    # Персонажи
    char_docs, char_sources = [], []
    for f in sorted((root / "content" / "characters").glob("*/character.yaml")):
        rel, _d = src(f)
        doc = load_yaml(f)
        c_errs = registry.validate(doc, rel)
        if c_errs:
            errors.extend(c_errs)
            continue
        char_docs.append((rel, doc))
        char_sources.append((rel, inputs[rel]))

    renames_path = root / "content" / "renames.yaml"
    renames_src = src(renames_path)
    renames = load_yaml(renames_path)

    # Реестр выпущенных id (G7/C16): сцены из него, отсутствующие в сборке,
    # получают shim-метки (сейв неустановленного пака не должен падать в crash).
    registry_scenes: list[str] = []
    id_registry_path = root / "content" / "registry" / "id_registry.json"
    overrides_sources = [renames_src]
    if id_registry_path.is_file():
        rel, _d = src(id_registry_path)
        try:
            registry_scenes = list(
                json.loads(id_registry_path.read_text(encoding="utf-8")).get("scenes") or [])
        except Exception:
            errors.append(f"{rel}: не парсится как JSON")
        overrides_sources.append((rel, inputs[rel]))

    # Локализация: ledger'ы (реестр меню), UI-строки, языки
    menus: dict[str, list] = {}
    ledger_dir = root / "loc" / "ledger"
    if ledger_dir.is_dir():
        for f in sorted(ledger_dir.glob("ch*.json")):
            rel, _d = src(f)
            ledger = json.loads(f.read_text(encoding="utf-8"))
            l_errs = registry.validate(ledger, rel)
            if l_errs:
                errors.extend(l_errs)
                continue
            for mid, menu in (ledger.get("menus") or {}).items():
                menus[mid] = list(menu["items"])
    ui_strings: dict[str, str] = {}
    strings_path = root / "content" / "ui" / "strings.yaml"
    if strings_path.is_file():
        rel, _d = src(strings_path)
        ui_strings = dict(load_yaml(strings_path).get("strings") or {})

    # UI-панели (ADR-0009): Frame-образы генерируемых скруглённых фонов
    ui_panels: dict = {}
    panels_path = root / "content" / "ui" / "panels.yaml"
    panels_src = proj_src
    if panels_path.is_file():
        rel, digest = src(panels_path)
        panels_doc = load_yaml(panels_path)
        errors.extend(registry.validate(panels_doc, rel))
        ui_panels = dict(panels_doc.get("panels") or {})
        panels_src = (rel, digest)
    source_lang = {"code": "source", "name": "Source"}
    loc_cfg_path = root / "loc" / "loc.yaml"
    if loc_cfg_path.is_file():
        rel, _d = src(loc_cfg_path)
        loc_cfg = load_yaml(loc_cfg_path)
        errors.extend(registry.validate(loc_cfg, rel))
        if isinstance(loc_cfg.get("source"), dict):
            source_lang = {"code": loc_cfg["source"].get("code", "source"),
                           "name": loc_cfg["source"].get("name", "Source")}

    # Миграции сейвов (G5)
    migrations = _collect_migrations(root, src, project, errors)

    # Локации
    locations = load_locations(root, src, registry, errors)

    # Паки (G9/G10) и главы: ядро + packs/<id>/chapters
    packs = _collect_packs(root, src, registry, errors)
    chapters, units, voice_docs, shots_docs = _collect_chapters(
        root, src, registry, errors, packs)
    if errors:
        raise CompileError(f"{len(errors)} ошибок:\n" + "\n".join(errors))

    char_ids = {doc["id"] for _, doc in char_docs}

    # Variable Registry (G5): {store.name} всех объявленных сохраняемых переменных —
    # сцены сверяют против него фактические чтения/записи (build-bridge).
    var_registry: set[str] = set()
    for _vrel, vdoc in var_docs:
        vstore = vdoc.get("store")
        for vname in (vdoc.get("vars") or {}):
            var_registry.add(f"{vstore}.{vname}")

    scene_rep = sc.SceneCompileReport()
    scene_outputs: dict[str, str] = {}
    if units:
        try:
            analysis = analyze_scene_files(root, [root / u.rpy_rel for u in units])
        except AnalyzeError as e:
            raise CompileError(str(e))
        known_scenes = {u.full_id for u in units}
        status_by_ch = {c["id"]: c["status"] for c in chapters}
        # Индекс образов для сверки ссылок show/scene/hide (раздел 3.9). Строится
        # из тех же источников, что и emit_images, но ДО эмиссии: опечатка в имени
        # обязана падать на сборке, а не исключением движка у игрока.
        from .images import build_image_index

        # Декларации шотов: сцена существует, переменные гардероба объявлены (G5).
        for s_ch, s_rel, s_doc in shots_docs:
            complain = (scene_rep.warnings.append
                        if status_by_ch.get(s_ch, "draft") == "draft"
                        else scene_rep.errors.append)
            if f"{s_ch}_{s_doc['scene']}" not in known_scenes:
                complain(f"{s_rel}: сцены {s_ch}_{s_doc['scene']} нет в сборке — "
                         f"шоты некому показывать")
            for shot_id, spec in sorted((s_doc.get("shots") or {}).items()):
                for layer, lspec in sorted(spec["layers"].items()):
                    var = lspec.get("var")
                    if var and var not in var_registry:
                        scene_rep.errors.append(
                            f"{s_rel}: {shot_id}: слой {layer}: переменной {var} нет "
                            f"в Variable Registry — гардероб не попадёт в сейв (G5)")

        image_index = build_image_index(root, locations, char_docs, shots_docs)
        for u in units:
            u.analysis = analysis.get(str(root / u.rpy_rel).replace("\\", "/"), None) or \
                         analysis.get(str(root / u.rpy_rel), None) or {}
            if not u.analysis:
                scene_rep.errors.append(f"{u.rpy_rel}: build-bridge не вернул анализ")

        # Голос (C5/§4.9): line_id манифестов сверяется с ФАКТИЧЕСКИМИ say-id из AST —
        # опечатка или пере-id-шеная реплика ловится сборкой, а не тишиной у игрока.
        # voiced = реплики, покрытые хотя бы одним языком: voice-оператор один, язык
        # выбирает рантайм (vn.voice_path) с деградацией до оригинала.
        say_ids_by_scene: dict[str, set[str]] = {
            u.full_id: {s["id"] for s in (u.analysis.get("say_list") or []) if s.get("id")}
            for u in units
        }
        voiced: set[str] = set()
        for v_ch, _v_lang, v_rel, v_doc in voice_docs:
            complain = (scene_rep.warnings.append
                        if status_by_ch.get(v_ch, "draft") == "draft"
                        else scene_rep.errors.append)
            for lid in sorted(v_doc.get("lines") or {}):
                scene_of_line = lid[: len("chNN_sNNN")]
                if scene_of_line not in say_ids_by_scene:
                    complain(f"{v_rel}: {lid}: сцены {scene_of_line} нет в сборке")
                elif lid not in say_ids_by_scene[scene_of_line]:
                    complain(
                        f"{v_rel}: {lid}: в сцене нет реплики с таким id — опечатка, "
                        f"реплика удалена или vn loc keys не прогнан")
                else:
                    voiced.add(lid)

        for u in units:
            if not u.analysis:
                continue
            for p in u.meta.get("participants") or []:
                if p not in char_ids:
                    scene_rep.errors.append(
                        f"{u.yaml_rel}: участник {p!r} не объявлен в content/characters/ "
                        f"(say упадёт NameError в рантайме)"
                    )
            dispatch = sc.validate_scene(
                u, known_scenes, status_by_ch.get(u.chapter_id, "draft"), scene_rep,
                var_registry=var_registry, image_index=image_index,
                audio_tracks=audio_tracks,
            )
            header = _header([(u.yaml_rel, inputs[u.yaml_rel]), (u.rpy_rel, inputs[u.rpy_rel])])
            scene_outputs[f"scenes/{u.chapter_id}/{u.full_id}.gen.rpy"] = sc.emit_scene(
                u, dispatch, audio_tracks, locations, scene_rep, header,
                voiced={lid for lid in voiced if lid.startswith(u.full_id + "_")},
            )
        # title_key глав обязан существовать в strings.yaml (иначе в меню — сырой ключ)
        for c in chapters:
            if c["title_key"] not in ui_strings:
                result.warnings.append(
                    f"{c['id']}: title_key {c['title_key']!r} нет в content/ui/strings.yaml — "
                    f"в меню глав отобразится сырой ключ"
                )
        # Валидация глав: entry_scene и scene_order существуют
        for c in chapters:
            ch_scenes = {u.short_id for u in units if u.chapter_id == c["id"]}
            complain = (scene_rep.warnings if c["status"] == "draft" else scene_rep.errors)
            if c["entry_scene"] not in ch_scenes:
                complain.append(f"{c['id']}: entry_scene {c['entry_scene']} не существует")
            for s in c.get("scene_order", []):
                if s not in ch_scenes:
                    complain.append(f"{c['id']}: scene_order: сцена {s} не существует")

    # Якоря достижений обязаны существовать: ачивка на удалённую сцену или
    # опечатанную переменную никогда не выдастся — это тихий мёртвый контент.
    if ach_docs:
        known_scene_ids = {u.full_id for u in units}
        known_chapters = {u.chapter_id for u in units}
        known_packs = set(packs) | {"core"}
        for arel, adoc in ach_docs:
            for aid, spec in sorted((adoc.get("achievements") or {}).items()):
                trigger = spec.get("trigger") or {}
                # Глава якоря отсутствует в сборке целиком — это частичная/пак-сборка,
                # а не опечатка: предупреждаем. Глава есть, а сцены/переменной нет —
                # ошибка (ачивка никогда не выдастся).
                if "scene" in trigger and trigger["scene"] not in known_scene_ids:
                    ch_of_scene = trigger["scene"][:4]
                    msg = (f"{arel}: достижение {aid}: сцены {trigger['scene']} "
                           f"не существует")
                    if ch_of_scene in known_chapters:
                        scene_rep.errors.append(msg)
                    else:
                        result.warnings.append(msg + " (главы нет в этой сборке)")
                if "var" in trigger and trigger["var"] not in var_registry:
                    store_name = trigger["var"].split(".", 1)[0]
                    msg = (f"{arel}: достижение {aid}: переменной {trigger['var']} "
                           f"нет в Variable Registry")
                    if not store_name.startswith("ch") or store_name in known_chapters:
                        scene_rep.errors.append(msg)
                    else:
                        result.warnings.append(msg + " (главы нет в этой сборке)")
                pack_id = spec.get("pack", "core")
                if pack_id not in known_packs:
                    scene_rep.errors.append(
                        f"{arel}: достижение {aid}: пак {pack_id!r} не установлен")
                for key in ("name_key", "desc_key"):
                    skey = spec.get(key)
                    if skey and skey not in ui_strings:
                        result.warnings.append(
                            f"{arel}: достижение {aid}: {key} {skey!r} нет в "
                            f"content/ui/strings.yaml — в UI отобразится сырой ключ")

    result.warnings.extend(scene_rep.warnings)
    if scene_rep.errors:
        raise CompileError(
            f"{len(scene_rep.errors)} ошибок компиляции сцен:\n" + "\n".join(scene_rep.errors)
        )

    # Реестр образов: фоны локаций + шоты + layeredimage из matrix и слоёв (G11)
    img_rep = ImagesReport()
    images_out = emit_images(root, locations, char_docs, img_rep,
                             _header(char_sources or [proj_src]),
                             shots_docs=shots_docs)
    result.warnings.extend(img_rep.warnings)
    if img_rep.errors:
        raise CompileError(
            f"{len(img_rep.errors)} ошибок реестра образов:\n" + "\n".join(img_rep.errors)
        )

    # Галерея (ADR-0010): валидация ассетов/превью/категорий/якорей — до записи
    # генерата, чтобы битая запись не доехала до игры.
    gal_errors: list[str] = []
    gallery_out = _emit_gallery(
        root, gal_docs, {u.full_id for u in units}, {c["id"] for c in chapters},
        var_registry, ui_strings, result, gal_errors, gal_sources or [proj_src],
        renames=renames)
    if gal_errors:
        raise CompileError(
            f"{len(gal_errors)} ошибок галереи:\n" + "\n".join(gal_errors))

    outputs: dict[str, str] = {
        "registry/images.gen.rpy": images_out,
        "version.gen.rpy": _emit_version(project, git_sha(root), [proj_src]),
        "render.gen.rpy": _emit_render(root, [proj_src]),
        "platform.gen.rpy": _emit_platform(project, packs, [proj_src]),
        "state/defaults.gen.rpy": _emit_defaults(project, var_docs, [proj_src] + var_sources),
        "state/snapshot.gen.rpy": _emit_snapshot(var_docs, [proj_src] + var_sources),
        "state/migrations.gen.rpy": _emit_migrations(migrations, [proj_src]),
        "registry/audio.gen.rpy": _emit_audio(audio_docs, audio_sources or [proj_src]),
        "registry/ui_frames.gen.rpy": _emit_ui_frames(ui_panels, [panels_src]),
        "registry/achievements.gen.rpy": _emit_achievements(
            ach_docs, ach_sources or [proj_src]),
        "registry/gallery.gen.rpy": gallery_out,
        "registry/chapters.gen.rpy": sc.emit_chapter_registry(
            sorted(chapters, key=lambda c: c["id"]), packs, _header([proj_src])
        ),
        "registry/scenes.gen.rpy": sc.emit_scene_registry(units, _header([proj_src])),
        "registry/characters.gen.rpy": sc.emit_characters(char_docs, _header(char_sources or [proj_src])),
        "registry/menus.gen.rpy": _emit_menus(menus, ui_strings, source_lang, [proj_src]),
        "registry/overrides.gen.rpy": _emit_overrides(
            renames, overrides_sources, registry_scenes=registry_scenes,
            known_scenes={u.full_id for u in units}),
    }
    outputs.update(scene_outputs)
    if chapters:
        outputs["screens/chapter_select.gen.rpy"] = sc.emit_chapter_select(_header([proj_src]))

    old_manifest_path = gen / MANIFEST_NAME
    old_outputs: set[str] = set()
    if old_manifest_path.is_file():
        try:
            old_outputs = set(json.loads(old_manifest_path.read_text(encoding="utf-8"))["outputs"])
        except Exception:
            pass

    # Режим --check (G1): вычислить выходы в память, сравнить с диском, НИЧЕГО не писать.
    if check:
        for rel, text in sorted(outputs.items()):
            path = gen / rel
            if not path.is_file() or _stale_key(rel, path.read_bytes()) != _stale_key(
                rel, text.encode("utf-8")
            ):
                result.stale.append(rel)
        for orphan in sorted(old_outputs - set(outputs)):
            if (gen / orphan).is_file():
                result.stale.append(f"{orphan} (осиротел)")
        return result

    # Точечная очистка (G6): осиротевшие выходы прошлого манифеста + их .rpyc.
    for orphan in sorted(old_outputs - set(outputs)):
        for path in (gen / orphan, (gen / orphan).with_suffix(".rpyc")):
            if path.is_file():
                path.unlink()
                result.deleted.append(path.relative_to(gen).as_posix())

    # Запись: неизменённые файлы не трогаются байтово (G6).
    out_hashes: dict[str, str] = {}
    for rel, text in sorted(outputs.items()):
        data = text.encode("utf-8")
        out_hashes[rel] = _b3(data)
        path = gen / rel
        if path.is_file() and path.read_bytes() == data:
            result.skipped.append(rel)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        result.written.append(rel)

    manifest = {
        "schema": "gen_manifest@1",
        "tool": __version__,
        "inputs": dict(sorted(inputs.items())),
        "outputs": out_hashes,
    }
    gen.mkdir(parents=True, exist_ok=True)
    old_manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=1, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return result
